version: '3.8'
services:
  app:
    image: user-api-app
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: task_2
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgresdemo
    ports:
      - "5432:5432"